before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null
- bash ci/composer_install.sh > /dev/null

test:app:
  image: asteris/apache-php-mongo
  script:
  - phpunit ox/tests --color --coverage-text

# test:5.6:
#   image: php:5.6
#   script:
#   - phpunit ox/tests --color --coverage-text
#
# test:7.0:
#   image: php:7.0
#   script:
#   - phpunit ox/tests --color --coverage-text
